language: node_js

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - 10

install:
  - yarn global add travis-ci-cloudfront-invalidation
  - yarn

addons:
  sonarcloud:
    organization: "wvandolah" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN

script:
  - yarn build
  - sonar-scanner

deploy:
  - provider: s3
    access_key_id: $AWS_KEY
    secret_access_key: $AWS_SECRET
    bucket: 'teamstatus.wvandolah.com'
    skip_cleanup: true
    acl: public_read
    local_dir: build
    on:
      branch: master
  - provider: s3
    access_key_id: $AWS_KEY
    secret_access_key: $AWS_SECRET
    bucket: 'teamstatus-dev.wvandolah.com'
    skip_cleanup: true
    acl: public_read
    local_dir: build
    on:
      branch: dev


after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_KEY -s $AWS_SECRET -c $AWS_CLOUDFRONT_DIST_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST -o 'master,dev'